import 'package:flutter/material.dart';

List<String> imageList = [
  'assets/images/image1.jpg',
  'assets/images/image2.jpg',
  'assets/images/image3.jpg',
  'assets/images/image4.jpg',
  'assets/images/image1.jpg',
  'assets/images/image2.jpg',
  'assets/images/image3.jpg',
  'assets/images/image4.jpg',
  'assets/images/image1.jpg',
  'assets/images/image2.jpg',
  'assets/images/image3.jpg',
  'assets/images/image4.jpg',
];
List<String> productTitle = [
  'Warm Zipper',
  'Knitted Woo!',
  'Zipper Win',
  'Child Win',
  'Warm Zipper',
  'Knitted Woo!',
  'Zipper Win',
  'Child Win',
  'Warm Zipper',
  'Knitted Woo!',
  'Zipper Win',
  'Child Win',
];
List<String> productPrice = [
  '\$300',
  '\$650',
  '\$50',
  '\$100',
  '\$300',
  '\$650',
  '\$50',
  '\$100',
  '\$300',
  '\$650',
  '\$50',
  '\$100',
];
List<String> reviews = [
  '54',
  '120',
  '542',
  '34',
  '54',
  '120',
  '542',
  '34',
  '54',
  '120',
  '542',
  '34',
];
List productRating = [
  4.5,
  4.0,
  3.5,
  4.5,
  4.5,
  4.0,
  3.5,
  4.5,
  4.5,
  4.0,
  3.5,
  4.5,
];
List productColors = [
  Colors.red,
  Colors.green,
  Colors.blue,
  Colors.amber,
  Colors.red,
  Colors.green,
  Colors.blue,
  Colors.amber,
  Colors.red,
  Colors.green,
  Colors.blue,
  Colors.amber,
];